name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1
      
      - name: Check syntax
        run: make syntax-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Neovim
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/v0.11.4/nvim-linux-x86_64.tar.gz
          tar xzf nvim-linux-x86_64.tar.gz
          echo "$PWD/nvim-linux64/bin" >> $GITHUB_PATH
      
      - name: Check Neovim version
        run: nvim --version
      
      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      
      - name: Lint
        run: make lint
      
      - name: Health check
        run: make test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install stylua
        run: |
          wget https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip
          unzip stylua-linux-x86_64.zip
          chmod +x stylua
          sudo mv stylua /usr/local/bin/
      
      - name: Check formatting
        run: |
          stylua --check lua/traverse-lsp.lua lua/traverse-lsp/ plugin/
          if [ $? -ne 0 ]; then
            echo "Code is not formatted. Run 'make format' locally."
            exit 1
          fi